"""Build an Ultralytics-format train/val split for project-497 (task #1).

Ultralytics resolves label paths by substituting the last `/images/` -> `/labels/`
in each image path, so the split must be a mirrored tree:

    <out>/images/{train,val}/*.png|jpg
    <out>/labels/{train,val}/*.txt   (remapped class ids)

Images are hard-linked (os.link, no admin needed on NTFS), not copied. The 9
zero-example classes are dropped for v1 by remapping to a contiguous 64-class id
space unless --keep-all is passed. Deterministic seeded split.
"""
from __future__ import annotations

import argparse
import json
import os
import random
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DS = ROOT / "datasets" / "project-497"
IMG_DIR = DS / "images"
LBL_DIR = DS / "labels"


def _clamp_box(cx: float, cy: float, w: float, h: float):
    """Clamp a normalized xywh box to the image by clamping its corners to [0,1]
    and recomputing center/size. Returns None if the result is degenerate."""
    x1, y1 = max(0.0, cx - w / 2), max(0.0, cy - h / 2)
    x2, y2 = min(1.0, cx + w / 2), min(1.0, cy + h / 2)
    nw, nh = x2 - x1, y2 - y1
    if nw <= 1e-4 or nh <= 1e-4:
        return None
    return (x1 + nw / 2, y1 + nh / 2, nw, nh)


def _link_or_copy(src: Path, dst: Path) -> None:
    if dst.exists():
        dst.unlink()
    try:
        os.link(src, dst)
    except OSError:
        import shutil
        shutil.copy2(src, dst)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--val-frac", type=float, default=0.15)
    # A held-out test split is not optional once experiments start accumulating.
    # Repeatedly selecting the best result on one val set eventually produces the
    # target number by selection rather than by learning -- near 0.95 on 907
    # images the standard error is ~0.7pp, which a few dozen experiments will
    # comfortably exploit. Test is scored ONCE, at the end.
    ap.add_argument("--test-frac", type=float, default=0.15)
    ap.add_argument("--seed", type=int, default=1234)
    ap.add_argument("--keep-all", action="store_true", help="keep all 73 classes incl. zero-example")
    ap.add_argument("--out", default=str(DS / "yolo"))
    args = ap.parse_args()

    classes = (DS / "classes.txt").read_text(encoding="utf-8").splitlines()

    counts = Counter()
    for lf in LBL_DIR.glob("*.txt"):
        for ln in lf.read_text().splitlines():
            ln = ln.strip()
            if ln:
                counts[int(ln.split()[0])] += 1

    kept_ids = list(range(len(classes))) if args.keep_all else [
        i for i in range(len(classes)) if counts.get(i, 0) > 0]
    remap = {old: new for new, old in enumerate(kept_ids)}
    kept_names = [classes[i] for i in kept_ids]

    out_dir = Path(args.out)
    splits_wanted = ["train", "val"] + (["test"] if args.test_frac > 0 else [])
    for kind in ("images", "labels"):
        for s in splits_wanted:
            (out_dir / kind / s).mkdir(parents=True, exist_ok=True)

    img_by_stem = {p.stem: p for p in IMG_DIR.iterdir() if p.is_file()}

    # collect (image, remapped_label_lines) pairs; clamp out-of-bounds boxes
    pairs = []
    clamped_boxes = dropped_boxes = 0
    for lf in sorted(LBL_DIR.glob("*.txt")):
        img = img_by_stem.get(lf.stem)
        if img is None:
            continue
        out_lines = []
        for ln in lf.read_text().splitlines():
            ln = ln.strip()
            if not ln:
                continue
            parts = ln.split()
            cid = int(parts[0])
            if cid not in remap:
                continue
            cx, cy, w, h = (float(x) for x in parts[1:5])
            if cx - w / 2 < 0 or cy - h / 2 < 0 or cx + w / 2 > 1 or cy + h / 2 > 1:
                box = _clamp_box(cx, cy, w, h)
                if box is None:
                    dropped_boxes += 1
                    continue
                cx, cy, w, h = box
                clamped_boxes += 1
            out_lines.append(f"{remap[cid]} {cx:.6f} {cy:.6f} {w:.6f} {h:.6f}")
        if not out_lines:
            continue
        pairs.append((img, out_lines))

    rng = random.Random(args.seed)
    rng.shuffle(pairs)
    n_val = int(len(pairs) * args.val_frac)
    n_test = int(len(pairs) * args.test_frac)
    splits = [
        ("val", pairs[:n_val]),
        ("test", pairs[n_val:n_val + n_test]),
        ("train", pairs[n_val + n_test:]),
    ]
    if n_test == 0:
        splits = [(k, v) for k, v in splits if k != "test"]

    for split, items in splits:
        for img, lines in items:
            _link_or_copy(img, out_dir / "images" / split / img.name)
            (out_dir / "labels" / split / (img.stem + ".txt")).write_text(
                "\n".join(lines) + "\n", encoding="utf-8")

    yaml = f"""# Auto-generated by scripts/build_split.py — do not edit by hand.
path: {out_dir.resolve().as_posix()}
train: images/train
val: images/val
nc: {len(kept_names)}
names:
"""
    for i, name in enumerate(kept_names):
        yaml += f"  {i}: {json.dumps(name)}\n"
    (out_dir / "data.yaml").write_text(yaml, encoding="utf-8")

    meta = {
        "n_images": len(pairs),
        "n_train": len(pairs) - n_val - n_test,
        "n_val": n_val,
        "n_test": n_test,
        "test_policy": "scored ONCE at the end; never used for model selection",
        "nc": len(kept_names),
        "dropped_classes": [classes[i] for i in range(len(classes)) if i not in remap],
        "clamped_boxes": clamped_boxes,
        "dropped_degenerate_boxes": dropped_boxes,
    }
    (out_dir / "split_meta.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    print(json.dumps(meta, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
