"""Carve a single-source dataset out of the pooled split (task #3 follow-up).

The pooled gate failed at 0.44 solve rate, but the per-source breakdown ranges
0.164 to 0.841 -- the dataset is ~10 CAPTCHA generators sharing one label space.
Two explanations remain and they demand opposite responses:

  (a) POOLING hurts. One model splitting capacity across ten visual styles does
      worse on each than a dedicated model would. => route by source, ship N
      small models, and the 95% target survives.
  (b) The hard styles are INTRINSICALLY hard. A dedicated model does no better.
      => no scoping trick saves the target for those styles.

This builds a mirrored Ultralytics tree containing only images of one pixel size
(the generator proxy), reusing the already-clamped labels from the pooled split
so the two runs differ in exactly one variable: the data mixture.

Labels keep the pooled 64-class id space on purpose. Shrinking the label space
to the classes present in one source would improve solve rate for free, which
would confound the comparison with the pooled run.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "datasets" / "project-497" / "yolo"


def _link_or_copy(src: Path, dst: Path) -> None:
    if dst.exists():
        dst.unlink()
    try:
        os.link(src, dst)
    except OSError:
        import shutil
        shutil.copy2(src, dst)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--size", default="230x60", help="WxH image size selecting the source")
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    from PIL import Image

    want = tuple(int(v) for v in args.size.lower().split("x"))
    out_dir = Path(args.out) if args.out else SRC.parent / f"src_{args.size}"
    for sub in ("images/train", "images/val", "labels/train", "labels/val"):
        (out_dir / sub).mkdir(parents=True, exist_ok=True)

    counts = {}
    for split in ("train", "val"):
        n = 0
        for p in sorted((SRC / "images" / split).iterdir()):
            if not p.is_file():
                continue
            with Image.open(p) as im:
                if im.size != want:
                    continue
            lbl = SRC / "labels" / split / (p.stem + ".txt")
            if not lbl.exists():
                continue
            _link_or_copy(p, out_dir / "images" / split / p.name)
            _link_or_copy(lbl, out_dir / "labels" / split / lbl.name)
            n += 1
        counts[split] = n

    # reuse the pooled data.yaml class block verbatim -- same 64-class id space
    pooled = (SRC / "data.yaml").read_text(encoding="utf-8")
    names_block = pooled[pooled.index("nc:"):]
    (out_dir / "data.yaml").write_text(
        f"# Auto-generated by scripts/build_source_split.py (source {args.size})\n"
        f"path: {out_dir.resolve().as_posix()}\n"
        f"train: images/train\nval: images/val\n{names_block}",
        encoding="utf-8")

    print(json.dumps({"size": args.size, "out": str(out_dir), **counts}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
